library(devtools)

check_man()

test()
test(filter = "config")
test(filter = "find_srcpkgs")
test(filter = "graph")
test(filter = "examples")
test(filter = "pkg_check")
test(filter = "pkg_load")
test(filter = "pkg_test")
test(filter = "pkg_utils")
test(filter = "pkgs_check")
test(filter = "pkgs_deps")
test(filter = "pkgs_test")
test(filter = "project_root")
test(filter = "srcpkg$")
test(filter = "srcpkgs")
check()

options(width = Sys.getenv("COLUMNS", 80))

rmarkdown::render("testing_and_checking.Rmd")
build_vignettes()
run_examples()
run_examples(run_donttest = TRUE)
